# Generated by Django 5.2.1 on 2025-06-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.IntegerField()),
                ('admission_number', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('admission_year', models.IntegerField()),
                ('passout_year', models.IntegerField()),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('borrowed_books', models.JSONField(default=dict)),
                ('book_requests', models.JSONField(default=dict)),
                ('enquiries', models.JSONField(default=dict)),
            ],
        ),
    ]
