# Generated by Django 5.2.1 on 2025-06-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_issuedbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedbook',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issuedbook',
            name='status',
            field=models.CharField(choices=[('borrowed', 'Borrowed'), ('collected', 'Collected')], default='borrowed', max_length=20),
        ),
    ]
