# Generated by Django 5.2.1 on 2025-06-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_issuedbook_return_date_alter_issuedbook_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedbook',
            name='collection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issuedbook',
            name='collection_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issuedbook',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issuedbook',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issuedbook',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('collected', 'Collected'), ('returned', 'Returned'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
    ]
