# Generated by Django 5.2.1 on 2025-06-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedbook',
            name='collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
