# Generated by Django 5.2.1 on 2025-06-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AddField(
            model_name='book',
            name='book_id',
            field=models.CharField(default='TEMP', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
