# Generated by Django 5.2.1 on 2025-06-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_bookrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
