# Generated by Django 5.2.1 on 2025-06-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, default='profile_photos/default_profile.png', upload_to='profile_photos/'),
        ),
    ]
